name: CI/CD Pipeline

on:
  push:
   

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run check

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Create build folder
        run: |
          mkdir -p build
          echo "Build successful" > build/status.txt
          echo "Checking build folder:"
          ls -lrt build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_folder
          path: build/

  deploy:
    runs-on: self-hosted
    needs: [test, build]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build_folder
          path: build/

      - name: Show artifact files
        run: |
          ls -lrt build/

     

      - name: Install dependencies
        run: npm install

      - name: Restart Application with PM2
        run: |
          pm2 status || true
          pm2 delete node-app || true
          pm2 start "npm start" --name node-app
          pm2 save